export interface EntitySprite {
  name: string;
  displayName: string;
  type: string;
  gridSize: {
    // Size of the entity, in grid units
    north: { width: number; height: number };
    east: { width: number; height: number };
    south: { width: number; height: number };
    west: { width: number; height: number };
  };
  origingOffset: {
    // Offset from the grid position to the 0,0 point of the sprite, in pixels
    north: { x: number; y: number };
    east: { x: number; y: number };
    south: { x: number; y: number };
    west: { x: number; y: number };
  };
  spriteScale: number; // Scale of the sprite
  spritePath: string; // Path to the sprite
  spriteOffset: {
    // Offset from the 0,0 point of the sprite to the 0,0 of the correct orientation, in pixels
    north: { x: number; y: number };
    east: { x: number; y: number };
    south: { x: number; y: number };
    west: { x: number; y: number };
  };
  spriteSize: {
    // Size of the sprite, in pixels
    north: { width: number; height: number };
    east: { width: number; height: number };
    south: { width: number; height: number };
    west: { width: number; height: number };
  };
}

export interface IconSprite {
  name: string;
  displayName: string;
  type: string;
  spritePath: string;
  spriteSize: { width: number; height: number };
  style?: React.CSSProperties;
}

export interface OperatorSprite {
  name: string;
  displayName: string;
  type: string;
  spriteSize: { width: number; height: number };
  origingOffset: {
    // Offset from the grid position to the 0,0 point of the sprite, in pixels
    north: { x: number; y: number };
    east: { x: number; y: number };
    south: { x: number; y: number };
    west: { x: number; y: number };
  };
  spriteScale: number; // Scale of the sprite
  spritePath: string; // Path to the sprite
  spriteOffset: { x: number; y: number };
  style?: React.CSSProperties;
}

const getBasePath = () => {
  if (process.env.NODE_ENV === "production") {
    return "./img/";
  } else {
    return "./circuitorio/img/";
  }
};

const basePath = getBasePath();

const operators: { [key: string]: OperatorSprite } = {
  ">": {
    name: ">",
    displayName: "Greater Than",
    type: "decider-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 28, y: 25 }, east: { x: 47, y: 11 }, south: { x: 29, y: 21 }, west: { x: 33, y: 13 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: 0, y: -44 },
  },
  "<": {
    name: "<",
    displayName: "Less Than",
    type: "decider-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 28, y: 25 }, east: { x: 47, y: 11 }, south: { x: 29, y: 21 }, west: { x: 33, y: 13 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -30, y: -44 },
  },
  "=": {
    name: "=",
    displayName: "Equal",
    type: "decider-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 28, y: 25 }, east: { x: 47, y: 11 }, south: { x: 29, y: 21 }, west: { x: 33, y: 13 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -60, y: -44 },
  },
  ">=": {
    name: ">=",
    displayName: "Greater Than or Equal",
    type: "decider-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 28, y: 25 }, east: { x: 47, y: 11 }, south: { x: 29, y: 21 }, west: { x: 33, y: 13 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -150, y: -44 },
  },
  "<=": {
    name: "<=",
    displayName: "Less Than or Equal",
    type: "decider-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 28, y: 25 }, east: { x: 47, y: 11 }, south: { x: 29, y: 21 }, west: { x: 33, y: 13 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -120, y: -44 },
  },
  "!=": {
    name: "!=",
    displayName: "Not Equal",
    type: "decider-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 28, y: 25 }, east: { x: 47, y: 11 }, south: { x: 29, y: 21 }, west: { x: 33, y: 13 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -90, y: -44 },
  },
  "+": {
    name: "+",
    displayName: "Add",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -30, y: 0 },
  },
  "-": {
    name: "-",
    displayName: "Subtract",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -60, y: 0 },
  },
  "*": {
    name: "*",
    displayName: "Multiply",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -90, y: 0 },
  },
  "/": {
    name: "/",
    displayName: "Divide",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -120, y: 0 },
  },
  "%": {
    name: "%",
    displayName: "Modulo",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -150, y: 0 },
  },
  "^": {
    name: "^",
    displayName: "Power",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: 0, y: -22 },
  },
  AND: {
    name: "AND",
    displayName: "AND Logical Gate",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -90, y: -22 },
  },
  OR: {
    name: "OR",
    displayName: "OR Logical Gate",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -120, y: -22 },
  },
  XOR: {
    name: "XOR",
    displayName: "XOR Logical Gate",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -150, y: -22 },
  },
  "<<": {
    name: "<<",
    displayName: "Left Shift",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -30, y: -22 },
  },
  ">>": {
    name: ">>",
    displayName: "Right Shift",
    type: "arithmetic-operator",
    spriteSize: { width: 30, height: 22 },
    origingOffset: { north: { x: 22, y: 28 }, east: { x: 40, y: 14 }, south: { x: 23, y: 27 }, west: { x: 34, y: 15 } },
    spriteScale: 1,
    spritePath: `${basePath}base/graphics/hr-combinator-displays.png`,
    spriteOffset: { x: -60, y: -22 },
  },
};

const entities: { [key: string]: EntitySprite } = {
  "arithmetic-combinator": {
    name: "arithmetic-combinator",
    displayName: "Arithmetic Combinator",
    type: "entity",
    gridSize: {
      north: { width: 1, height: 2 },
      east: { width: 2, height: 1 },
      south: { width: 1, height: 2 },
      west: { width: 2, height: 1 },
    },
    origingOffset: { north: { x: -5, y: 17 }, east: { x: 9, y: -16 }, south: { x: -5, y: 17 }, west: { x: 15, y: -15 } },
    spriteOffset: {
      north: { x: -34, y: 0 },
      east: { x: -160, y: 0 },
      south: { x: -322, y: 0 },
      west: { x: -454, y: 0 },
    },
    spritePath: `${basePath}base/graphics/hr-arithmetic-combinator.png`,
    spriteScale: 0.5,
    spriteSize: {
      north: { width: 77, height: 109 },
      east: { width: 105, height: 89 },
      south: { width: 79, height: 102 },
      west: { width: 107, height: 91 },
    },
  },
  "decider-combinator": {
    name: "decider-combinator",
    displayName: "Decider Combinator",
    type: "entity",
    gridSize: {
      north: { width: 1, height: 2 },
      east: { width: 2, height: 1 },
      south: { width: 1, height: 2 },
      west: { width: 2, height: 1 },
    },
    origingOffset: { north: { x: -10, y: 18 }, east: { x: 3, y: -18 }, south: { x: -11, y: 23 }, west: { x: 16, y: -19 } },
    spriteOffset: {
      north: { x: -35, y: -5 },
      east: { x: -172, y: -2 },
      south: { x: -346, y: -10 },
      west: { x: -497, y: 0 },
    },
    spritePath: `${basePath}base/graphics/hr-decider-combinator.png`,
    spriteScale: 0.5,
    spriteSize: {
      north: { width: 86, height: 111 },
      east: { width: 118, height: 91 },
      south: { width: 87, height: 103 },
      west: { width: 117, height: 94 },
    },
  },
  "constant-combinator": {
    name: "constant-combinator",
    displayName: "Constant Combinator",
    type: "entity",
    gridSize: {
      north: { width: 1, height: 1 },
      east: { width: 1, height: 1 },
      south: { width: 1, height: 1 },
      west: { width: 1, height: 1 },
    },
    origingOffset: { north: { x: -10, y: -5 }, east: { x: -12, y: -10 }, south: { x: -8, y: 2 }, west: { x: -8, y: -9 } },
    spriteOffset: {
      north: { x: -16, y: -4 },
      east: { x: -127, y: 0 },
      south: { x: -245, y: -11 },
      west: { x: -359, y: 0 },
    },
    spritePath: `${basePath}base/graphics/hr-constant-combinator.png`,
    spriteScale: 0.5,
    spriteSize: {
      north: { width: 82, height: 75 },
      east: { width: 90, height: 85 },
      south: { width: 82, height: 74 },
      west: { width: 82, height: 83 },
    },
  },
};

const icons: { [key: string]: IconSprite } = {
  effects: {
    name: "effects",
    displayName: "Effects",
    type: "item-group",
    spritePath: `${basePath}base/graphics/item-group/effects.png`,
    spriteSize: { width: 128, height: 128 },
  },
  fluids: {
    name: "fluids",
    displayName: "Fluids",
    type: "item-group",
    spritePath: `${basePath}base/graphics/item-group/fluids.png`,
    spriteSize: { width: 128, height: 128 },
  },
  "intermediate-products": {
    name: "intermediate-products",
    displayName: "Intermediate Products",
    type: "item-group",
    spritePath: `${basePath}base/graphics/item-group/intermediate-products.png`,
    spriteSize: { width: 128, height: 128 },
  },
  logistics: {
    name: "logistics",
    displayName: "Logistics",
    type: "item-group",
    spritePath: `${basePath}base/graphics/item-group/logistics.png`,
    spriteSize: { width: 128, height: 128 },
  },
  military: {
    name: "military",
    displayName: "Military",
    type: "item-group",
    spritePath: `${basePath}base/graphics/item-group/military.png`,
    spriteSize: { width: 128, height: 128 },
  },
  production: {
    name: "production",
    displayName: "Production",
    type: "item-group",
    spritePath: `${basePath}base/graphics/item-group/production.png`,
    spriteSize: { width: 128, height: 128 },
  },
  signals: {
    name: "signals",
    displayName: "Signals",
    type: "item-group",
    spritePath: `${basePath}base/graphics/item-group/signals.png`,
    spriteSize: { width: 128, height: 128 },
  },
  signal_0: {
    name: "signal_0",
    displayName: "Signal 0",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_0.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_1: {
    name: "signal_1",
    displayName: "Signal 1",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_1.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_2: {
    name: "signal_2",
    displayName: "Signal 2",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_2.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_3: {
    name: "signal_3",
    displayName: "Signal 3",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_3.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_4: {
    name: "signal_4",
    displayName: "Signal 4",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_4.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_5: {
    name: "signal_5",
    displayName: "Signal 5",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_5.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_6: {
    name: "signal_6",
    displayName: "Signal 6",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_6.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_7: {
    name: "signal_7",
    displayName: "Signal 7",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_7.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_8: {
    name: "signal_8",
    displayName: "Signal 8",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_8.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_9: {
    name: "signal_9",
    displayName: "Signal 9",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_9.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_A: {
    name: "signal_A",
    displayName: "Signal A",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_A.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_B: {
    name: "signal_B",
    displayName: "Signal B",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_B.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_C: {
    name: "signal_C",
    displayName: "Signal C",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_C.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_D: {
    name: "signal_D",
    displayName: "Signal D",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_D.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_E: {
    name: "signal_E",
    displayName: "Signal E",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_E.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_F: {
    name: "signal_F",
    displayName: "Signal F",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_F.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_G: {
    name: "signal_G",
    displayName: "Signal G",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_G.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_H: {
    name: "signal_H",
    displayName: "Signal H",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_H.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_I: {
    name: "signal_I",
    displayName: "Signal I",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_I.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_J: {
    name: "signal_J",
    displayName: "Signal J",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_J.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_K: {
    name: "signal_K",
    displayName: "Signal K",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_K.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_L: {
    name: "signal_L",
    displayName: "Signal L",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_L.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_M: {
    name: "signal_M",
    displayName: "Signal M",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_M.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_N: {
    name: "signal_N",
    displayName: "Signal N",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_N.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_O: {
    name: "signal_O",
    displayName: "Signal O",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_O.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_P: {
    name: "signal_P",
    displayName: "Signal P",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_P.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_Q: {
    name: "signal_Q",
    displayName: "Signal Q",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_Q.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_R: {
    name: "signal_R",
    displayName: "Signal R",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_R.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_S: {
    name: "signal_S",
    displayName: "Signal S",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_S.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_T: {
    name: "signal_T",
    displayName: "Signal T",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_T.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_U: {
    name: "signal_U",
    displayName: "Signal U",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_U.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_V: {
    name: "signal_V",
    displayName: "Signal V",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_V.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_W: {
    name: "signal_W",
    displayName: "Signal W",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_W.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_X: {
    name: "signal_X",
    displayName: "Signal X",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_X.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_Y: {
    name: "signal_Y",
    displayName: "Signal Y",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_Y.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_Z: {
    name: "signal_Z",
    displayName: "Signal Z",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_Z.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_blue: {
    name: "signal_blue",
    displayName: "Signal Blue",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_blue.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_cyan: {
    name: "signal_cyan",
    displayName: "Signal Cyan",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_cyan.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_green: {
    name: "signal_green",
    displayName: "Signal Green",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_green.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_grey: {
    name: "signal_grey",
    displayName: "Signal Grey",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_grey.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_pink: {
    name: "signal_pink",
    displayName: "Signal Pink",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_pink.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_red: {
    name: "signal_red",
    displayName: "Signal Red",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_red.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_white: {
    name: "signal_white",
    displayName: "Signal White",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_white.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_yellow: {
    name: "signal_yellow",
    displayName: "Signal Yellow",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_yellow.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_black: {
    name: "signal_black",
    displayName: "Signal Black",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_black.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_anything: {
    name: "signal_anything",
    displayName: "Signal Anything",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_anything.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_everything: {
    name: "signal_everything",
    displayName: "Signal Everything",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_everything.png`,
    spriteSize: { width: 32, height: 32 },
  },
  signal_each: {
    name: "signal_each",
    displayName: "Signal Each",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/signal/signal_each.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "advanced-oil-processing": {
    name: "advanced-oil-processing",
    displayName: "Advanced Oil Processing",
    type: "recipe",
    spritePath: `${basePath}base/graphics/icons/fluid/advanced-oil-processing.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "basic-oil-processing": {
    name: "basic-oil-processing",
    displayName: "Basic Oil Processing",
    type: "recipe",
    spritePath: `${basePath}base/graphics/icons/fluid/basic-oil-processing.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "coal-liquefaction": {
    name: "coal-liquefaction",
    displayName: "Coal Liquefaction",
    type: "recipe",
    spritePath: `${basePath}base/graphics/icons/fluid/coal-liquefaction.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "crude-oil": {
    name: "crude-oil",
    displayName: "Crude Oil",
    type: "fluid",
    spritePath: `${basePath}base/graphics/icons/fluid/crude-oil.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "heavy-oil": {
    name: "heavy-oil",
    displayName: "Heavy Oil",
    type: "fluid",
    spritePath: `${basePath}base/graphics/icons/fluid/heavy-oil.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "heavy-oil-cracking": {
    name: "heavy-oil-cracking",
    displayName: "Heavy Oil Cracking",
    type: "recipe",
    spritePath: `${basePath}base/graphics/icons/fluid/heavy-oil-cracking.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "light-oil": {
    name: "light-oil",
    displayName: "Light Oil",
    type: "fluid",
    spritePath: `${basePath}base/graphics/icons/fluid/light-oil.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "light-oil-cracking": {
    name: "light-oil-cracking",
    displayName: "Light Oil Cracking",
    type: "recipe",
    spritePath: `${basePath}base/graphics/icons/fluid/light-oil-cracking.png`,
    spriteSize: { width: 32, height: 32 },
  },
  lubricant: {
    name: "lubricant",
    displayName: "Lubricant",
    type: "fluid",
    spritePath: `${basePath}base/graphics/icons/fluid/lubricant.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "petroleum-gas": {
    name: "petroleum-gas",
    displayName: "Petroleum Gas",
    type: "fluid",
    spritePath: `${basePath}base/graphics/icons/fluid/petroleum-gas.png`,
    spriteSize: { width: 32, height: 32 },
  },
  steam: {
    name: "steam",
    displayName: "Steam",
    type: "fluid",
    spritePath: `${basePath}base/graphics/icons/fluid/steam.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "sulfuric-acid": {
    name: "sulfuric-acid",
    displayName: "Sulfuric Acid",
    type: "fluid",
    spritePath: `${basePath}base/graphics/icons/fluid/sulfuric-acid.png`,
    spriteSize: { width: 32, height: 32 },
  },
  water: {
    name: "water",
    displayName: "Water",
    type: "fluid",
    spritePath: `${basePath}base/graphics/icons/fluid/water.png`,
    spriteSize: { width: 32, height: 32 },
  },
  accumulator: {
    name: "accumulator",
    displayName: "Accumulator",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/accumulator.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "advanced-circuit": {
    name: "advanced-circuit",
    displayName: "Advanced Circuit",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/advanced-circuit.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "arithmetic-combinator": {
    name: "arithmetic-combinator",
    displayName: "Arithmetic Combinator",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/arithmetic-combinator.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "artillery-shell": {
    name: "artillery-shell",
    displayName: "Artillery Shell",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/artillery-shell.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "artillery-turret": {
    name: "artillery-turret",
    displayName: "Artillery Turret",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/artillery-turret.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "artillery-wagon": {
    name: "artillery-wagon",
    displayName: "Artillery Wagon",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/artillery-wagon.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "assembling-machine-1": {
    name: "assembling-machine-1",
    displayName: "Assembling Machine 1",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/assembling-machine-1.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "assembling-machine-2": {
    name: "assembling-machine-2",
    displayName: "Assembling Machine 2",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/assembling-machine-2.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "assembling-machine-3": {
    name: "assembling-machine-3",
    displayName: "Assembling Machine 3",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/assembling-machine-3.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "atomic-bomb": {
    name: "atomic-bomb",
    displayName: "Atomic Bomb",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/atomic-bomb.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "automation-science-pack": {
    name: "automation-science-pack",
    displayName: "Automation Science Pack",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/automation-science-pack.png`,
    spriteSize: { width: 32, height: 32 },
  },
  battery: {
    name: "battery",
    displayName: "Battery",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/battery.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "battery-equipment": {
    name: "battery-equipment",
    displayName: "Battery Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/battery-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "battery-mk2-equipment": {
    name: "battery-mk2-equipment",
    displayName: "Battery Mk2 Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/battery-mk2-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  beacon: {
    name: "beacon",
    displayName: "Beacon",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/beacon.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "belt-immunity-equipment": {
    name: "belt-immunity-equipment",
    displayName: "Belt Immunity Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/belt-immunity-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "big-electric-pole": {
    name: "big-electric-pole",
    displayName: "Big Electric Pole",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/big-electric-pole.png`,
    spriteSize: { width: 32, height: 32 },
  },
  blueprint: {
    name: "blueprint",
    displayName: "Blueprint",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/blueprint.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "blueprint-book": {
    name: "blueprint-book",
    displayName: "Blueprint Book",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/blueprint-book.png`,
    spriteSize: { width: 32, height: 32 },
  },
  boiler: {
    name: "boiler",
    displayName: "Boiler",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/boiler.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "burner-inserter": {
    name: "burner-inserter",
    displayName: "Burner Inserter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/burner-inserter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "burner-mining-drill": {
    name: "burner-mining-drill",
    displayName: "Burner Mining Drill",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/burner-mining-drill.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "cannon-shell": {
    name: "cannon-shell",
    displayName: "Cannon Shell",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/cannon-shell.png`,
    spriteSize: { width: 32, height: 32 },
  },
  car: {
    name: "car",
    displayName: "Car",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/car.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "cargo-wagon": {
    name: "cargo-wagon",
    displayName: "Cargo Wagon",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/cargo-wagon.png`,
    spriteSize: { width: 32, height: 32 },
  },
  centrifuge: {
    name: "centrifuge",
    displayName: "Centrifuge",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/centrifuge.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "checked-green": {
    name: "checked-green",
    displayName: "Checked Green",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/checked-green.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "chemical-plant": {
    name: "chemical-plant",
    displayName: "Chemical Plant",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/chemical-plant.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "chemical-science-pack": {
    name: "chemical-science-pack",
    displayName: "Chemical Science Pack",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/chemical-science-pack.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "cliff-explosives": {
    name: "cliff-explosives",
    displayName: "Cliff Explosives",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/cliff-explosives.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "cluster-grenade": {
    name: "cluster-grenade",
    displayName: "Cluster Grenade",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/cluster-grenade.png`,
    spriteSize: { width: 32, height: 32 },
  },
  coal: {
    name: "coal",
    displayName: "Coal",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/coal.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "combat-shotgun": {
    name: "combat-shotgun",
    displayName: "Combat Shotgun",
    type: "gun",
    spritePath: `${basePath}base/graphics/icons/combat-shotgun.png`,
    spriteSize: { width: 32, height: 32 },
  },
  concrete: {
    name: "concrete",
    displayName: "Concrete",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/concrete.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "constant-combinator": {
    name: "constant-combinator",
    displayName: "Constant Combinator",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/constant-combinator.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "construction-robot": {
    name: "construction-robot",
    displayName: "Construction Robot",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/construction-robot.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "copper-cable": {
    name: "copper-cable",
    displayName: "Copper Cable",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/copper-cable.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "copper-ore": {
    name: "copper-ore",
    displayName: "Copper Ore",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/copper-ore.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "copper-plate": {
    name: "copper-plate",
    displayName: "Copper Plate",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/copper-plate.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "decider-combinator": {
    name: "decider-combinator",
    displayName: "Decider Combinator",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/decider-combinator.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "deconstruction-planner": {
    name: "deconstruction-planner",
    displayName: "Deconstruction Planner",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/deconstruction-planner.png`,
    spriteSize: { width: 32, height: 32 },
  },
  defender: {
    name: "defender",
    displayName: "Defender",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/defender.png`,
    spriteSize: { width: 32, height: 32 },
  },
  destroyer: {
    name: "destroyer",
    displayName: "Destroyer",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/destroyer.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "discharge-defense-equipment": {
    name: "discharge-defense-equipment",
    displayName: "Discharge Defense Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/discharge-defense-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "discharge-defense-equipment-controller": {
    name: "discharge-defense-equipment-controller",
    displayName: "Discharge Defense Equipment Controller",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/discharge-defense-equipment-controller.png`,
    spriteSize: { width: 32, height: 32 },
  },
  distractor: {
    name: "distractor",
    displayName: "Distractor",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/distractor.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "effectivity-module": {
    name: "effectivity-module",
    displayName: "Effectivity Module",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/effectivity-module.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "effectivity-module-2": {
    name: "effectivity-module-2",
    displayName: "Effectivity Module 2",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/effectivity-module-2.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "effectivity-module-3": {
    name: "effectivity-module-3",
    displayName: "Effectivity Module 3",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/effectivity-module-3.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "electric-engine-unit": {
    name: "electric-engine-unit",
    displayName: "Electric Engine Unit",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/electric-engine-unit.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "electric-furnace": {
    name: "electric-furnace",
    displayName: "Electric Furnace",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/electric-furnace.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "electric-mining-drill": {
    name: "electric-mining-drill",
    displayName: "Electric Mining Drill",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/electric-mining-drill.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "electronic-circuit": {
    name: "electronic-circuit",
    displayName: "Electronic Circuit",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/electronic-circuit.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "energy-shield-equipment": {
    name: "energy-shield-equipment",
    displayName: "Energy Shield Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/energy-shield-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "energy-shield-mk2-equipment": {
    name: "energy-shield-mk2-equipment",
    displayName: "Energy Shield Mk2 Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/energy-shield-mk2-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "engine-unit": {
    name: "engine-unit",
    displayName: "Engine Unit",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/engine-unit.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "exoskeleton-equipment": {
    name: "exoskeleton-equipment",
    displayName: "Exoskeleton Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/exoskeleton-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "explosive-cannon-shell": {
    name: "explosive-cannon-shell",
    displayName: "Explosive Cannon Shell",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/explosive-cannon-shell.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "explosive-rocket": {
    name: "explosive-rocket",
    displayName: "Explosive Rocket",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/explosive-rocket.png`,
    spriteSize: { width: 32, height: 32 },
  },
  explosives: {
    name: "explosives",
    displayName: "Explosives",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/explosives.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "explosive-uranium-cannon-shell": {
    name: "explosive-uranium-cannon-shell",
    displayName: "Explosive Uranium Cannon Shell",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/explosive-uranium-cannon-shell.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "express-splitter": {
    name: "express-splitter",
    displayName: "Express Splitter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/express-splitter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "express-transport-belt": {
    name: "express-transport-belt",
    displayName: "Express Transport Belt",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/express-transport-belt.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "express-underground-belt": {
    name: "express-underground-belt",
    displayName: "Express Underground Belt",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/express-underground-belt.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "fast-inserter": {
    name: "fast-inserter",
    displayName: "Fast Inserter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/fast-inserter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "fast-splitter": {
    name: "fast-splitter",
    displayName: "Fast Splitter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/fast-splitter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "fast-transport-belt": {
    name: "fast-transport-belt",
    displayName: "Fast Transport Belt",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/fast-transport-belt.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "fast-underground-belt": {
    name: "fast-underground-belt",
    displayName: "Fast Underground Belt",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/fast-underground-belt.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "filter-inserter": {
    name: "filter-inserter",
    displayName: "Filter Inserter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/filter-inserter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "firearm-magazine": {
    name: "firearm-magazine",
    displayName: "Firearm Magazine",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/firearm-magazine.png`,
    spriteSize: { width: 32, height: 32 },
  },
  fish: {
    name: "fish",
    displayName: "Fish",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/fish.png`,
    spriteSize: { width: 32, height: 32 },
  },
  flamethrower: {
    name: "flamethrower",
    displayName: "Flamethrower",
    type: "gun",
    spritePath: `${basePath}base/graphics/icons/flamethrower.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "flamethrower-ammo": {
    name: "flamethrower-ammo",
    displayName: "Flamethrower Ammo",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/flamethrower-ammo.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "flamethrower-turret": {
    name: "flamethrower-turret",
    displayName: "Flamethrower Turret",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/flamethrower-turret.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "fluid-wagon": {
    name: "fluid-wagon",
    displayName: "Fluid Wagon",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/fluid-wagon.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "flying-robot-frame": {
    name: "flying-robot-frame",
    displayName: "Flying Robot Frame",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/flying-robot-frame.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "fusion-reactor-equipment": {
    name: "fusion-reactor-equipment",
    displayName: "Fusion Reactor Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/fusion-reactor-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  gate: {
    name: "gate",
    displayName: "Gate",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/gate.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "green-wire": {
    name: "green-wire",
    displayName: "Green Wire",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/green-wire.png`,
    spriteSize: { width: 32, height: 32 },
  },
  grenade: {
    name: "grenade",
    displayName: "Grenade",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/grenade.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "gun-turret": {
    name: "gun-turret",
    displayName: "Gun Turret",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/gun-turret.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "hazard-concrete": {
    name: "hazard-concrete",
    displayName: "Hazard Concrete",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/hazard-concrete.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "heat-boiler": {
    name: "heat-boiler",
    displayName: "Heat Boiler",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/heat-boiler.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "heat-pipe": {
    name: "heat-pipe",
    displayName: "Heat Pipe",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/heat-pipe.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "heavy-armor": {
    name: "heavy-armor",
    displayName: "Heavy Armor",
    type: "armor",
    spritePath: `${basePath}base/graphics/icons/heavy-armor.png`,
    spriteSize: { width: 32, height: 32 },
  },
  info: {
    name: "info",
    displayName: "Info",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/info.png`,
    spriteSize: { width: 32, height: 32 },
  },
  inserter: {
    name: "inserter",
    displayName: "Inserter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/inserter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "iron-chest": {
    name: "iron-chest",
    displayName: "Iron Chest",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/iron-chest.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "iron-gear-wheel": {
    name: "iron-gear-wheel",
    displayName: "Iron Gear Wheel",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/iron-gear-wheel.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "iron-ore": {
    name: "iron-ore",
    displayName: "Iron Ore",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/iron-ore.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "iron-plate": {
    name: "iron-plate",
    displayName: "Iron Plate",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/iron-plate.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "iron-stick": {
    name: "iron-stick",
    displayName: "Iron Stick",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/iron-stick.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "kovarex-enrichment-process": {
    name: "kovarex-enrichment-process",
    displayName: "Kovarex Enrichment Process",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/kovarex-enrichment-process.png`,
    spriteSize: { width: 32, height: 32 },
  },
  lab: {
    name: "lab",
    displayName: "Lab",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/lab.png`,
    spriteSize: { width: 32, height: 32 },
  },
  landfill: {
    name: "landfill",
    displayName: "Landfill",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/landfill.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "land-mine": {
    name: "land-mine",
    displayName: "Land Mine",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/land-mine.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "laser-turret": {
    name: "laser-turret",
    displayName: "Laser Turret",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/laser-turret.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "light-armor": {
    name: "light-armor",
    displayName: "Light Armor",
    type: "armor",
    spritePath: `${basePath}base/graphics/icons/light-armor.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "list-dot": {
    name: "list-dot",
    displayName: "List Dot",
    type: "signal",
    spritePath: `${basePath}base/graphics/icons/list-dot.png`,
    spriteSize: { width: 32, height: 32 },
  },
  locomotive: {
    name: "locomotive",
    displayName: "Locomotive",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/locomotive.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "logistic-chest-active-provider": {
    name: "logistic-chest-active-provider",
    displayName: "Logistic Chest Active Provider",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/logistic-chest-active-provider.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "logistic-chest-buffer": {
    name: "logistic-chest-buffer",
    displayName: "Logistic Chest Buffer",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/logistic-chest-buffer.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "logistic-chest-passive-provider": {
    name: "logistic-chest-passive-provider",
    displayName: "Logistic Chest Passive Provider",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/logistic-chest-passive-provider.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "logistic-chest-requester": {
    name: "logistic-chest-requester",
    displayName: "Logistic Chest Requester",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/logistic-chest-requester.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "logistic-chest-storage": {
    name: "logistic-chest-storage",
    displayName: "Logistic Chest Storage",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/logistic-chest-storage.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "logistic-robot": {
    name: "logistic-robot",
    displayName: "Logistic Robot",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/logistic-robot.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "logistic-science-pack": {
    name: "logistic-science-pack",
    displayName: "Logistic Science Pack",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/logistic-science-pack.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "long-handed-inserter": {
    name: "long-handed-inserter",
    displayName: "Long Handed Inserter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/long-handed-inserter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "low-density-structure": {
    name: "low-density-structure",
    displayName: "Low Density Structure",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/low-density-structure.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "medium-electric-pole": {
    name: "medium-electric-pole",
    displayName: "Medium Electric Pole",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/medium-electric-pole.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "military-science-pack": {
    name: "military-science-pack",
    displayName: "Military Science Pack",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/military-science-pack.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "modular-armor": {
    name: "modular-armor",
    displayName: "Modular Armor",
    type: "armor",
    spritePath: `${basePath}base/graphics/icons/modular-armor.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "night-vision-equipment": {
    name: "night-vision-equipment",
    displayName: "Night Vision Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/night-vision-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "nuclear-fuel": {
    name: "nuclear-fuel",
    displayName: "Nuclear Fuel",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/nuclear-fuel.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "nuclear-fuel-reprocessing": {
    name: "nuclear-fuel-reprocessing",
    displayName: "Nuclear Fuel Reprocessing",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/nuclear-fuel-reprocessing.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "nuclear-reactor": {
    name: "nuclear-reactor",
    displayName: "Nuclear Reactor",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/nuclear-reactor.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "offshore-pump": {
    name: "offshore-pump",
    displayName: "Offshore Pump",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/offshore-pump.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "oil-refinery": {
    name: "oil-refinery",
    displayName: "Oil Refinery",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/oil-refinery.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "personal-laser-defense-equipment": {
    name: "personal-laser-defense-equipment",
    displayName: "Personal Laser Defense Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/personal-laser-defense-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "personal-roboport-equipment": {
    name: "personal-roboport-equipment",
    displayName: "Personal Roboport Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/personal-roboport-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "personal-roboport-mk2-equipment": {
    name: "personal-roboport-mk2-equipment",
    displayName: "Personal Roboport Mk2 Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/personal-roboport-mk2-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "piercing-rounds-magazine": {
    name: "piercing-rounds-magazine",
    displayName: "Piercing Rounds Magazine",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/piercing-rounds-magazine.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "piercing-shotgun-shell": {
    name: "piercing-shotgun-shell",
    displayName: "Piercing Shotgun Shell",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/piercing-shotgun-shell.png`,
    spriteSize: { width: 32, height: 32 },
  },
  pipe: {
    name: "pipe",
    displayName: "Pipe",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/pipe.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "pipe-to-ground": {
    name: "pipe-to-ground",
    displayName: "Pipe To Ground",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/pipe-to-ground.png`,
    spriteSize: { width: 32, height: 32 },
  },
  pistol: {
    name: "pistol",
    displayName: "Pistol",
    type: "gun",
    spritePath: `${basePath}base/graphics/icons/pistol.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "plastic-bar": {
    name: "plastic-bar",
    displayName: "Plastic Bar",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/plastic-bar.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "poison-capsule": {
    name: "poison-capsule",
    displayName: "Poison Capsule",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/poison-capsule.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "power-armor": {
    name: "power-armor",
    displayName: "Power Armor",
    type: "armor",
    spritePath: `${basePath}base/graphics/icons/power-armor.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "power-armor-mk2": {
    name: "power-armor-mk2",
    displayName: "Power Armor Mk2",
    type: "armor",
    spritePath: `${basePath}base/graphics/icons/power-armor-mk2.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "power-switch": {
    name: "power-switch",
    displayName: "Power Switch",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/power-switch.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "processing-unit": {
    name: "processing-unit",
    displayName: "Processing Unit",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/processing-unit.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "production-science-pack": {
    name: "production-science-pack",
    displayName: "Production Science Pack",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/production-science-pack.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "productivity-module": {
    name: "productivity-module",
    displayName: "Productivity Module",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/productivity-module.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "productivity-module-2": {
    name: "productivity-module-2",
    displayName: "Productivity Module 2",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/productivity-module-2.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "productivity-module-3": {
    name: "productivity-module-3",
    displayName: "Productivity Module 3",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/productivity-module-3.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "programmable-speaker": {
    name: "programmable-speaker",
    displayName: "Programmable Speaker",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/programmable-speaker.png`,
    spriteSize: { width: 32, height: 32 },
  },
  pump: {
    name: "pump",
    displayName: "Pump",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/pump.png`,
    spriteSize: { width: 32, height: 32 },
  },
  pumpjack: {
    name: "pumpjack",
    displayName: "Pumpjack",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/pumpjack.png`,
    spriteSize: { width: 32, height: 32 },
  },
  radar: {
    name: "radar",
    displayName: "Radar",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/radar.png`,
    spriteSize: { width: 32, height: 32 },
  },
  rail: {
    name: "rail",
    displayName: "Rail",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/rail.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "rail-chain-signal": {
    name: "rail-chain-signal",
    displayName: "Rail Chain Signal",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/rail-chain-signal.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "rail-signal": {
    name: "rail-signal",
    displayName: "Rail Signal",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/rail-signal.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "red-wire": {
    name: "red-wire",
    displayName: "Red Wire",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/red-wire.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "refined-concrete": {
    name: "refined-concrete",
    displayName: "Refined Concrete",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/refined-concrete.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "refined-hazard-concrete": {
    name: "refined-hazard-concrete",
    displayName: "Refined Hazard Concrete",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/refined-hazard-concrete.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "repair-pack": {
    name: "repair-pack",
    displayName: "Repair Pack",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/repair-pack.png`,
    spriteSize: { width: 32, height: 32 },
  },
  roboport: {
    name: "roboport",
    displayName: "Roboport",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/roboport.png`,
    spriteSize: { width: 32, height: 32 },
  },
  rocket: {
    name: "rocket",
    displayName: "Rocket",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/rocket.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "rocket-control-unit": {
    name: "rocket-control-unit",
    displayName: "Rocket Control Unit",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/rocket-control-unit.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "rocket-fuel": {
    name: "rocket-fuel",
    displayName: "Rocket Fuel",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/rocket-fuel.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "rocket-launcher": {
    name: "rocket-launcher",
    displayName: "Rocket Launcher",
    type: "gun",
    spritePath: `${basePath}base/graphics/icons/rocket-launcher.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "rocket-part": {
    name: "rocket-part",
    displayName: "Rocket Part",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/rocket-part.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "rocket-silo": {
    name: "rocket-silo",
    displayName: "Rocket Silo",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/rocket-silo.png`,
    spriteSize: { width: 32, height: 32 },
  },
  satellite: {
    name: "satellite",
    displayName: "Satellite",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/satellite.png`,
    spriteSize: { width: 32, height: 32 },
  },
  shotgun: {
    name: "shotgun",
    displayName: "Shotgun",
    type: "gun",
    spritePath: `${basePath}base/graphics/icons/shotgun.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "shotgun-shell": {
    name: "shotgun-shell",
    displayName: "Shotgun Shell",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/shotgun-shell.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "slowdown-capsule": {
    name: "slowdown-capsule",
    displayName: "Slowdown Capsule",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/slowdown-capsule.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "small-electric-pole": {
    name: "small-electric-pole",
    displayName: "Small Electric Pole",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/small-electric-pole.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "small-lamp": {
    name: "small-lamp",
    displayName: "Small Lamp",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/small-lamp.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "solar-panel": {
    name: "solar-panel",
    displayName: "Solar Panel",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/solar-panel.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "solar-panel-equipment": {
    name: "solar-panel-equipment",
    displayName: "Solar Panel Equipment",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/solar-panel-equipment.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "solid-fuel": {
    name: "solid-fuel",
    displayName: "Solid Fuel",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/solid-fuel.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "space-science-pack": {
    name: "space-science-pack",
    displayName: "Space Science Pack",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/space-science-pack.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "speed-module": {
    name: "speed-module",
    displayName: "Speed Module",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/speed-module.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "speed-module-2": {
    name: "speed-module-2",
    displayName: "Speed Module 2",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/speed-module-2.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "speed-module-3": {
    name: "speed-module-3",
    displayName: "Speed Module 3",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/speed-module-3.png`,
    spriteSize: { width: 32, height: 32 },
  },
  spidertron: {
    name: "spidertron",
    displayName: "Spidertron",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/spidertron.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "spidertron-remote": {
    name: "spidertron-remote",
    displayName: "Spidertron Remote",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/spidertron-remote.png`,
    spriteSize: { width: 32, height: 32 },
  },
  splitter: {
    name: "splitter",
    displayName: "Splitter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/splitter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "stack-filter-inserter": {
    name: "stack-filter-inserter",
    displayName: "Stack Filter Inserter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/stack-filter-inserter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "stack-inserter": {
    name: "stack-inserter",
    displayName: "Stack Inserter",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/stack-inserter.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "steam-engine": {
    name: "steam-engine",
    displayName: "Steam Engine",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/steam-engine.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "steam-turbine": {
    name: "steam-turbine",
    displayName: "Steam Turbine",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/steam-turbine.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "steel-axe": {
    name: "steel-axe",
    displayName: "Steel Axe",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/steel-axe.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "steel-chest": {
    name: "steel-chest",
    displayName: "Steel Chest",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/steel-chest.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "steel-furnace": {
    name: "steel-furnace",
    displayName: "Steel Furnace",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/steel-furnace.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "steel-plate": {
    name: "steel-plate",
    displayName: "Steel Plate",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/steel-plate.png`,
    spriteSize: { width: 32, height: 32 },
  },
  stone: {
    name: "stone",
    displayName: "Stone",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/stone.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "stone-brick": {
    name: "stone-brick",
    displayName: "Stone Brick",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/stone-brick.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "stone-furnace": {
    name: "stone-furnace",
    displayName: "Stone Furnace",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/stone-furnace.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "storage-tank": {
    name: "storage-tank",
    displayName: "Storage Tank",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/storage-tank.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "submachine-gun": {
    name: "submachine-gun",
    displayName: "Submachine Gun",
    type: "gun",
    spritePath: `${basePath}base/graphics/icons/submachine-gun.png`,
    spriteSize: { width: 32, height: 32 },
  },
  substation: {
    name: "substation",
    displayName: "Substation",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/substation.png`,
    spriteSize: { width: 32, height: 32 },
  },
  sulfur: {
    name: "sulfur",
    displayName: "Sulfur",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/sulfur.png`,
    spriteSize: { width: 32, height: 32 },
  },
  tank: {
    name: "tank",
    displayName: "Tank",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/tank.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "train-stop": {
    name: "train-stop",
    displayName: "Train Stop",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/train-stop.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "transport-belt": {
    name: "transport-belt",
    displayName: "Transport Belt",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/transport-belt.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "underground-belt": {
    name: "underground-belt",
    displayName: "Underground Belt",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/underground-belt.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "upgrade-planner": {
    name: "upgrade-planner",
    displayName: "Upgrade Planner",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/upgrade-planner.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "uranium-235": {
    name: "uranium-235",
    displayName: "Uranium 235",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/uranium-235.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "uranium-238": {
    name: "uranium-238",
    displayName: "Uranium 238",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/uranium-238.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "uranium-cannon-shell": {
    name: "uranium-cannon-shell",
    displayName: "Uranium Cannon Shell",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/uranium-cannon-shell.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "uranium-fuel-cell": {
    name: "uranium-fuel-cell",
    displayName: "Uranium Fuel Cell",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/uranium-fuel-cell.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "uranium-ore": {
    name: "uranium-ore",
    displayName: "Uranium Ore",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/uranium-ore.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "uranium-rounds-magazine": {
    name: "uranium-rounds-magazine",
    displayName: "Uranium Rounds Magazine",
    type: "ammo",
    spritePath: `${basePath}base/graphics/icons/uranium-rounds-magazine.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "used-up-uranium-fuel-cell": {
    name: "used-up-uranium-fuel-cell",
    displayName: "Used Up Uranium Fuel Cell",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/used-up-uranium-fuel-cell.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "utility-science-pack": {
    name: "utility-science-pack",
    displayName: "Utility Science Pack",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/utility-science-pack.png`,
    spriteSize: { width: 32, height: 32 },
  },
  wall: {
    name: "wall",
    displayName: "Wall",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/wall.png`,
    spriteSize: { width: 32, height: 32 },
  },
  wood: {
    name: "wood",
    displayName: "Wood",
    type: "item",
    spritePath: `${basePath}base/graphics/icons/wood.png`,
    spriteSize: { width: 32, height: 32 },
  },
  "wooden-chest": {
    name: "wooden-chest",
    displayName: "Wooden Chest",
    type: "entity",
    spritePath: `${basePath}base/graphics/icons/wooden-chest.png`,
    spriteSize: { width: 32, height: 32 },
  },
};

export const OperatorSpriteProvider = (operatorId: string): OperatorSprite => {
  const operatorSprite = operators[operatorId];
  return operatorSprite;
};

export const SpriteProvider = (entityId: string): EntitySprite => {
  const entity = entities[entityId];
  return entity;
};

export const IconProvider = (iconId: string): IconSprite => {
  const icon = icons[iconId];
  icon.style = {
    width: `${icon.spriteSize.width}px`,
    height: `${icon.spriteSize.height}px`,
    scale: "0.9",
    backgroundImage: `url(${icon.spritePath})`,
    backgroundSize: "62px 32px",
    backgroundPosition: "0px 0px",
    backgroundRepeat: "no-repeat",
    marginLeft: "2px",
  };
  return icon;
};
